# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: <%= Rails.application.secrets.quarto_username %>
  password: <%= Rails.application.secrets.quarto_password %>

development:
  <<: *default
  database: capstone

test:
  <<: *default
  database: capstone

production:
  <<: *default
  database: <%= Rails.application.secrets.quarto_database %>
